<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>com.yeungzhy</groupId>
        <artifactId>yeed-cloud</artifactId>
        <version>20260501</version>
    </parent>

    <artifactId>yeed-common</artifactId>
    <packaging>pom</packaging>

    <modules>
        <module>yeed-common-cache</module>
        <module>yeed-common-core</module>
        <module>yeed-common-data</module>
        <module>yeed-common-security</module>
        <module>yeed-common-web</module>
    </modules>

    <dependencies>
        <dependency>
            <groupId>org.projectlombok</groupId>
            <artifactId>lombok</artifactId>
        </dependency>
    </dependencies>

</project>
